import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/components/providers/reactquery";
import { Wrapper } from "@/components/layouts/Wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <ReactQueryProvider>
        <body>
          <Wrapper>{children}</Wrapper>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
